AdLineup/Controllers/AdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Configuration;
using AdLineup.Models;

namespace AdLineup.Controllers
{
    public class AdsController : Controller
    {
        private LogManager logger = new LogManager();
        private AdLineupContext db = new AdLineupContext();

        // GET: AddBillboardToAd
        public ActionResult AddBillboardToAd(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            var billboardsAvailable = db.Billboards.ToList().Except(ad.Billboards.ToList()).ToList();
            ViewBag.BillboardId = new SelectList(billboardsAvailable, "Id", "Name");
            if (ad == null)
            {
                return HttpNotFound();
            }
            AdBillboardViewModel viewModel = new AdBillboardViewModel();
            viewModel.AdId = ad.Id;
            viewModel.Ad_Name = ad.Name;
            return View(viewModel);
        }

        // POST: Ads/AddBillboardToAd/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("AddBillboardToAd")]
        [ValidateAntiForgeryToken]
        public ActionResult AddBillboardToAdPost([Bind(Include = "AdId,Ad_Name,BillboardId,Billboard_Name")] AdBillboardViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Ad ad = db.Ads.Find(viewModel.AdId);
                Billboard billboard = db.Billboards.Find(viewModel.BillboardId);
                ad.Billboards.Add(billboard);
                db.Entry(ad).State = EntityState.Modified;
                db.SaveChanges();
                logger.Log("Ads/AddBillboardToAd/ - BillboardId:" + billboard.Id.ToString() + " to AdId: " + ad.Id.ToString());
                return RedirectToAction("Details", new { id = viewModel.AdId });
            }
            return View(viewModel);
        }

        // GET: RemoveBillboardFromAd
        public ActionResult RemoveBillboardFromAd(int? adId, int? billboardId)
        {
            if (adId == null || billboardId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(adId);
            Billboard billboard = db.Billboards.Find(billboardId);
            if (ad == null || billboard == null)
            {
                return HttpNotFound();
            }
            ad.Billboards.Remove(billboard);
            db.Entry(ad).State = EntityState.Modified;
            db.SaveChanges();
            logger.Log("Ads/RemoveBillboardFromAd/ - BillboardId:" + billboard.Id.ToString() + " from AdId: " + ad.Id.ToString());
            return RedirectToAction("Details", new { id = adId });
        }

        // GET: Ads
        public ActionResult Index()
        {
            string printerFriendlyUrl = WebConfigurationManager.AppSettings["AppEngineUrl"];
            if (printerFriendlyUrl.EndsWith("/")) { printerFriendlyUrl = printerFriendlyUrl.TrimEnd('/'); }
            printerFriendlyUrl += ":" + WebConfigurationManager.AppSettings["AppEnginePort"];
            printerFriendlyUrl += "/api/reports/AdsIndexPrinterFriendly";
            ViewBag.PrinterFriendlyUrl = printerFriendlyUrl;
            ViewBag.AppEngineTimeout = WebConfigurationManager.AppSettings["AppEngineTimeout"];
            return View(db.Ads.ToList());
        }

        // GET: Ads/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // GET: Ads/Create
        public ActionResult Create(int? id, string modelType)
        {
            if (modelType != null && modelType.Length > 0)
            {
            }
            else
            {
            }
            // modelType not always properly being passed as query string parameter so send it in ViewBag
            ViewBag.modelType = modelType;
            return View();
        }

        // POST: Ads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Index,FlightStart,FlightEnd,ImageFilename")] Ad ad, int? id, string modelType)
        {
            string controllerName = "";
            if (ModelState.IsValid)
            {
                db.Ads.Add(ad);
                db.SaveChanges();
                logger.Log("Ads/Create - AdId:" + ad.Id.ToString());
                if (modelType != null && modelType.Length > 0)
                {
                    if (modelType.Contains("Billboard"))
                    {
                        db.Billboards.Find(id).Ads.Add(ad);
                        db.SaveChanges();
                        logger.Log("Ads/Create added - AdId:" + ad.Id.ToString() + " to BillboardId: " + id.ToString());
                        controllerName = "Billboards";
                    }
                    return RedirectToAction("Details", controllerName, new { Id = id });
                }
                return RedirectToAction("Index");
            }

            return View(ad);
        }

        // GET: Ads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // POST: Ads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost([Bind(Include = "Id,Name,Index,FlightStart,FlightEnd,ImageFilename")] Ad ad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ad).State = EntityState.Modified;
                db.SaveChanges();
                logger.Log("Ads/Edit/ - AdId:" + ad.Id.ToString());
                return RedirectToAction("Index");
            }
            return View(ad);
        }

        // GET: Ads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // POST: Ads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            Ad ad = db.Ads.Find(id);
            db.Ads.Remove(ad);
            db.SaveChanges();
            logger.Log("Ads/Delete/ - AdId:" + ad.Id.ToString());
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdLineup/Views/Ads/AddBillboardToAd.cshtml
@model AdLineup.Models.AdBillboardViewModel

@{
    ViewBag.Title = "AddBillboardToAd";
}

<h2>Ad: @Html.DisplayFor(model => model.Ad_Name)</h2>
<h4>Add Billboard To Ad</h4>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.AdId)
        @Html.HiddenFor(model => model.Ad_Name)

        @if (((SelectList)ViewBag.BillboardId).Count() > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Billboard_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BillboardId", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <div class="col-md-offset-1 col-md-10">
                    @Html.Raw("<b>All available Billboards have been added to this Ad.</b>")
                </div>
            </div>
        }
    </div>
}

<div>
    @Html.ActionLink("Back to Ad Detail", "Details", new { id = Model.AdId } )
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdLineup/Views/Ads/Create.cshtml
@model AdLineup.Models.Ad

@{
    ViewBag.Title = "Create Ad";
@Styles.Render("~/Content/datetimepicker/css")
@Scripts.Render("~/bundles/datetimepicker")

}

<h2>Ad</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.Hidden("modelType", (object)Convert.ToString(ViewBag.modelType))
    
    <div class="form-horizontal">
        <h4>Create</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Index, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Index, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Index, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlightStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FlightStart, new { htmlAttributes = new { @class = "form-control", @id = "datetimepickerflightstart", @type = "text" } })
                @Html.ValidationMessageFor(model => model.FlightStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlightEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FlightEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FlightEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageFilename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript"> 
            $(function () { 
                $('#datetimepickerflightstart').datetimepicker({ 
                }); 
            }); 
</script>

AdLineup/Views/Ads/Delete.cshtml
@model AdLineup.Models.Ad

@{
    ViewBag.Title = "Delete Ad";
}

<h2>Ad: @Html.DisplayFor(model => model.Name)</h2>

<div>
    <h4>Delete</h4>
    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Index)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Index)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageFilename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFilename)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdLineup/Views/Ads/Details.cshtml
@model AdLineup.Models.Ad

@{
    ViewBag.Title = "Details Ad";
}

<h2>Ad: @Html.DisplayFor(model => model.Name)</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Index)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Index)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageFilename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageFilename)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<div>
    <hr />
    <h4>
        Billboards
        &nbsp&nbsp&nbsp
        <small>@Html.ActionLink("Add Billboard To Ad", "AddBillboardToAd", "Ads", new { id = Model.Id }, null)</small>
    </h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(modelBillboard => Model.Billboards.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(modelBillboard => Model.Billboards.FirstOrDefault().Location)
            </th>
            <th>
                @Html.DisplayNameFor(modelBillboard => Model.Billboards.FirstOrDefault().Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(modelBillboard => Model.Billboards.FirstOrDefault().Longitude)
            </th>
        <th></th>
        </tr>
@foreach (var billboard in Model.Billboards)    {
        <tr>
            <td>
                @Html.DisplayFor(modelBillboard => billboard.Name)
            </td>
            <td>
                @Html.DisplayFor(modelBillboard => billboard.Location)
            </td>
            <td>
                @Html.DisplayFor(modelBillboard => billboard.Latitude)
            </td>
            <td>
                @Html.DisplayFor(modelBillboard => billboard.Longitude)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Billboards", new { id = billboard.Id }, null)
 |
                @Html.ActionLink("Remove from List", "RemoveBillboardFromAd", "Ads", new { adId = Model.Id, billboardId = billboard.Id }, null )
            </td>
        </tr>
}
    </table>    
</div>

AdLineup/Views/Ads/Edit.cshtml
@model AdLineup.Models.Ad

@{
    ViewBag.Title = "Edit Ad";
@Styles.Render("~/Content/datetimepicker/css")
@Scripts.Render("~/bundles/datetimepicker")

}

<h2>Ad: @Html.DisplayFor(model => model.Name)</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Index, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Index, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Index, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlightStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FlightStart, new { htmlAttributes = new { @class = "form-control", @id = "datetimepickerflightstart", @type = "text" } })
                @Html.ValidationMessageFor(model => model.FlightStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlightEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FlightEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FlightEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageFilename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript"> 
            $(function () { 
                $('#datetimepickerflightstart').datetimepicker({ 
                }); 
            }); 
</script>

AdLineup/Views/Ads/Index.cshtml
@model IEnumerable<AdLineup.Models.Ad>

@{
    ViewBag.Title = "Index Ad";
}

<h2>Ads</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = 0, modelType = "" }, null) | 
    <a id="printerFriendlyLink" href="#">Printer Friendly View</a>
    <img id="printerFriendlyLoader" src="~/Content/images/linear-loader.gif" style="display: none;"/>
</p>
    <div id="printerFriendlyError" class="alert alert-danger" style="display: none;">
        <strong>Error:</strong>  Could not generate Printer Friendly View. Please try again.
    </div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Index)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlightStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlightEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageFilename)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Index)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FlightStart)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FlightEnd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageFilename)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<script src="~/Scripts/ViewScripts/index-view.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#printerFriendlyError").hide();
        storePrinterFriendlyData("@ViewBag.PrinterFriendlyUrl", "@ViewBag.AppEngineTimeout");
        $("#printerFriendlyLink").click(function () {
            viewReport(
                getPrinterFriendlyUrl(),
                getAppEngineTimeout(),
                $("#printerFriendlyError"),
                $("#printerFriendlyLink"),
                $("#printerFriendlyLoader")
            );
        });
    });
</script>