AdLineup/Controllers/BillboardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Configuration;
using AdLineup.Models;

namespace AdLineup.Controllers
{
    public class BillboardsController : Controller
    {
        private LogManager logger = new LogManager();
        private AdLineupContext db = new AdLineupContext();

        // Billboards/BillboardAdsFlowchartDiagram/1
        public ActionResult BillboardAdsFlowchartDiagram(int? id)
        {
            Billboard billboard = db.Billboards.Find(id);

            if (billboard.AdFlowchartDiagramData == null || billboard.AdFlowchartDiagramData.Length == 0)
            {
                Flowchart flowchart = BillboardAdsToFlowchart(billboard);
                billboard.AdFlowchartDiagramData = flowchart.ToJSON();
                db.Entry(billboard).State = EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.FlowchartTitle = "Ad Diagram for " + billboard.Name;
            ViewBag.FlowchartData = billboard.AdFlowchartDiagramData;
            return View(billboard);
        }

        // POST: Billboards/BillboardAdsFlowchartDiagram/1
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult BillboardAdsFlowchartDiagram([Bind(Include = "Id")] Billboard billboard, string flowchartData)
        {
            billboard = db.Billboards.Find(billboard.Id);
            if (flowchartData.Length > 0)
            {
                billboard.AdFlowchartDiagramData = flowchartData;
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = billboard.Id });
        }

        // BillboardAdsToFlowchart
        public static Flowchart BillboardAdsToFlowchart(Billboard billboard)
        {
            // converts the specified objects into a Flowchart object and returns it
            Flowchart flowchart = new Flowchart();
            FlowchartOperator fcOperator = null;
            FlowchartOperator fcOperatorPrevious = null;
            FlowchartConnector fcInput = null;
            FlowchartConnector fcOutput = null;
            FlowchartLink fcLink = null;
            int top = 0;
            int left = 0;
            int opCount = 0;

            // check for valid input
            if (billboard != null)
            {
                flowchart.Id = billboard.Id.ToString();
                // add operators
                opCount = 1;
                foreach (Ad ad in billboard.Ads)
                {
                    fcOperator = new FlowchartOperator();
                    fcOperator.Id = "op" + billboard.Id.ToString() + ad.Id.ToString();
                    fcOperator.Title = ad.Name;
                    fcOperator.Top = top;
                    fcOperator.Left = left;
                    fcOperator.ImageSource = ad.ImageFilename;
                    top += 20;
                    left += 200;
                    // inputs
                    fcInput = new FlowchartConnector();
                    fcInput.Id = fcOperator.Id + "in1";
                    fcInput.Label = "";
                    fcOperator.Inputs.Add(fcInput);
                    // outputs
                    fcOutput = new FlowchartConnector();
                    fcOutput.Id = fcOperator.Id + "out1";
                    fcOutput.Label = "";
                    fcOperator.Outputs.Add(fcOutput);
                    // popup
                    fcOperator.Popup.header = "<h2>" + ad.Name + "</h2>";
                    fcOperator.Popup.body = @"";
                    fcOperator.Popup.body += @"<p>Name: " + ad.Name.ToString() + "</p>";
                    fcOperator.Popup.body += @"<p>Flight Start: " + ad.FlightStart.ToString() + "</p>";
                    fcOperator.Popup.body += @"<p>Flight End: " + ad.FlightEnd.ToString() + "</p>";
                    fcOperator.Popup.body += @"<img src='" + ad.ImageFilename + "' alt='Image'>";
                    // add the operator
                    flowchart.Operators.Add(fcOperator);
                    opCount += 1;
                }

                // add links
                foreach (FlowchartOperator myOperator in flowchart.Operators)
                {
                    if (fcOperatorPrevious != null)
                    {
                        fcLink = new FlowchartLink();
                        fcLink.Id = myOperator.Id + "lnk1";
                        fcLink.FromOperatorId = fcOperatorPrevious.Id;
                        fcLink.FromConnectorId = fcOperatorPrevious.Outputs.FirstOrDefault().Id;
                        fcLink.ToOperatorId = myOperator.Id;
                        fcLink.ToConnectorId = myOperator.Inputs.FirstOrDefault().Id;
                        flowchart.Links.Add(fcLink);
                    }
                    fcOperatorPrevious = myOperator;
                }
            }
            return flowchart;
        } // BillboardAdsToFlowchart ()

        // GET: AddAdToBillboard
        public ActionResult AddAdToBillboard(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Billboard billboard = db.Billboards.Find(id);
            var adsAvailable = db.Ads.ToList().Except(billboard.Ads.ToList()).ToList();
            ViewBag.AdId = new SelectList(adsAvailable, "Id", "Name");
            if (billboard == null)
            {
                return HttpNotFound();
            }
            AdBillboardViewModel viewModel = new AdBillboardViewModel();
            viewModel.BillboardId = billboard.Id;
            viewModel.Billboard_Name = billboard.Name;
            return View(viewModel);
        }

        // POST: Billboards/AddAdToBillboard/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("AddAdToBillboard")]
        [ValidateAntiForgeryToken]
        public ActionResult AddAdToBillboardPost([Bind(Include = "BillboardId,Billboard_Name,AdId,Ad_Name")] AdBillboardViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Billboard billboard = db.Billboards.Find(viewModel.BillboardId);
                Ad ad = db.Ads.Find(viewModel.AdId);
                billboard.Ads.Add(ad);
                Flowchart flowchart = BillboardAdsToFlowchart(billboard);
                billboard.AdFlowchartDiagramData = flowchart.ToJSON();
                db.Entry(billboard).State = EntityState.Modified;
                db.SaveChanges();
                logger.Log("Billboards/AddAdToBillboard/ - AdId:" + ad.Id.ToString() + " to BillboardId: " + billboard.Id.ToString());
                return RedirectToAction("Details", new { id = viewModel.BillboardId });
            }
            return View(viewModel);
        }

        // GET: RemoveAdFromBillboard
        public ActionResult RemoveAdFromBillboard(int? billboardId, int? adId)
        {
            if (billboardId == null || adId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Billboard billboard = db.Billboards.Find(billboardId);
            Ad ad = db.Ads.Find(adId);
            if (billboard == null || ad == null)
            {
                return HttpNotFound();
            }
            billboard.Ads.Remove(ad);
                Flowchart flowchart = BillboardAdsToFlowchart(billboard);
                billboard.AdFlowchartDiagramData = flowchart.ToJSON();
            db.Entry(billboard).State = EntityState.Modified;
            db.SaveChanges();
            logger.Log("Billboards/RemoveAdFromBillboard/ - AdId:" + ad.Id.ToString() + " from BillboardId: " + billboard.Id.ToString());
            return RedirectToAction("Details", new { id = billboardId });
        }

        // GET: Billboards
        public ActionResult Index()
        {
            string printerFriendlyUrl = WebConfigurationManager.AppSettings["AppEngineUrl"];
            if (printerFriendlyUrl.EndsWith("/")) { printerFriendlyUrl = printerFriendlyUrl.TrimEnd('/'); }
            printerFriendlyUrl += ":" + WebConfigurationManager.AppSettings["AppEnginePort"];
            printerFriendlyUrl += "/api/reports/BillboardsIndexPrinterFriendly";
            ViewBag.PrinterFriendlyUrl = printerFriendlyUrl;
            ViewBag.AppEngineTimeout = WebConfigurationManager.AppSettings["AppEngineTimeout"];
            return View(db.Billboards.ToList());
        }

        // GET: Billboards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Billboard billboard = db.Billboards.Find(id);
            if (billboard == null)
            {
                return HttpNotFound();
            }
            return View(billboard);
        }

        // GET: Billboards/Create
        public ActionResult Create(int? id, string modelType)
        {
            if (modelType != null && modelType.Length > 0)
            {
            }
            else
            {
            }
            // modelType not always properly being passed as query string parameter so send it in ViewBag
            ViewBag.modelType = modelType;
            return View();
        }

        // POST: Billboards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Create")]

AdLineup/Views/Billboards/AddAdToBillboard.cshtml
@model AdLineup.Models.AdBillboardViewModel

@{
    ViewBag.Title = "AddAdToBillboard";
}

<h2>Billboard: @Html.DisplayFor(model => model.Billboard_Name)</h2>
<h4>Add Ad To Billboard</h4>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.BillboardId)
        @Html.HiddenFor(model => model.Billboard_Name)

        @if (((SelectList)ViewBag.AdId).Count() > 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Ad_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AdId", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <div class="col-md-offset-1 col-md-10">
                    @Html.Raw("<b>All available Ads have been added to this Billboard.</b>")
                </div>
            </div>
        }
    </div>
}

<div>
    @Html.ActionLink("Back to Billboard Detail", "Details", new { id = Model.BillboardId } )
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdLineup/Views/Billboards/BillboardAdsFlowchartDiagram.cshtml
@model AdLineup.Models.Billboard
@{
    ViewBag.Title = "BillboardAdsFlowchartDiagram";
}
@Styles.Render("~/Content/flowchart/css")
@Scripts.Render("~/bundles/flowchart")

<h2>Billboard Ads Diagram: @Model.Name</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Hidden("flowchartData", "")
    <div>
        @Html.ActionLink("Back to Details", "Details", new { id = Model.Id })
    </div>
    <hr />
    <div class="flowchart">
        <div class="flowchart-container panzoom" id="flowchart"></div>
    </div>
    <div id="modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="modal-header" class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Default Header</h4>
                </div>
                <div id="modal-body" class="modal-body">
                    <p>Default Body</p>
                </div>
                <div id="modal-footer" class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    var flowchartData = JSON.parse('@ViewBag.FlowchartData'.replace(/&quot;/g, '"'));
    $(document).ready(function () {
        $('#flowchart').flowchart({
            canUserMoveOperators: false,
            canUserEditLinks: false,
            data: flowchartData,
            defaultLinkColor: '#ff5e5e',
            multipleLinksOnInput: true,
            multipleLinksOnOutput: true,
            onAfterChange: function (changeType) {
                saveFlowchartData();
            },
            onLinkSelect: function () {
            },
            onOperatorSelect: function (operatorId) {
                $('#modal-header').html(flowchartData.operators[operatorId].operatorPopup.header);
                $('#modal-body').html(flowchartData.operators[operatorId].operatorPopup.body);
                $('#modal').modal('show');
            },
        });
    });

    function saveFlowchartData() {
        var $flowchart = $('#flowchart');
        document.getElementById('flowchartData').value = JSON.stringify($('#flowchart').flowchart('getData'));
    };

    var $panzoom = $(".panzoom").panzoom();
    $panzoom.parent().on('mousewheel.focal', function (e) {
        e.preventDefault();
        var delta = e.delta || e.originalEvent.wheelDelta;
        var zoomOut = delta ? delta < 0 : e.originalEvent.deltaY > 0;
        $panzoom.panzoom('zoom', zoomOut, {
            increment: 0.1,
            animate: false,
            focal: e,
        });
    });

</script>

AdLineup/Views/Billboards/Create.cshtml
@model AdLineup.Models.Billboard

@{
    ViewBag.Title = "Create Billboard";
@Styles.Render("~/Content/datetimepicker/css")
@Scripts.Render("~/bundles/datetimepicker")

}

<h2>Billboard</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.Hidden("modelType", (object)Convert.ToString(ViewBag.modelType))
    
    <div class="form-horizontal">
        <h4>Create</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (User.IsInRole("Admin"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.AdFlowchartDiagramData, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AdFlowchartDiagramData, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AdFlowchartDiagramData, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdLineup/Views/Billboards/Delete.cshtml
@model AdLineup.Models.Billboard

@{
    ViewBag.Title = "Delete Billboard";
}

<h2>Billboard: @Html.DisplayFor(model => model.Name)</h2>

<div>
    <h4>Delete</h4>
    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdFlowchartDiagramData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdFlowchartDiagramData)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdLineup/Views/Billboards/Details.cshtml
@model AdLineup.Models.Billboard

@{
    ViewBag.Title = "Details Billboard";
}

<h2>Billboard: @Html.DisplayFor(model => model.Name)</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        @if (User.IsInRole("Admin"))
        {
            <dt>
                @Html.DisplayNameFor(model => model.AdFlowchartDiagramData)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdFlowchartDiagramData)
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<div>
    <hr />
    <h4>
        Ads
        &nbsp&nbsp&nbsp
        <small>@Html.ActionLink("Add Ad To Billboard", "AddAdToBillboard", "Billboards", new { id = Model.Id }, null)</small>
        &nbsp&nbsp&nbsp
        <small>@Html.ActionLink("Ads Diagram", "BillboardAdsFlowchartDiagram", "Billboards", new { id = Model.Id }, null)</small>
    </h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(modelAd => Model.Ads.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(modelAd => Model.Ads.FirstOrDefault().Index)
            </th>
            <th>
                @Html.DisplayNameFor(modelAd => Model.Ads.FirstOrDefault().FlightStart)
            </th>
            <th>
                @Html.DisplayNameFor(modelAd => Model.Ads.FirstOrDefault().FlightEnd)
            </th>
            <th>
                @Html.DisplayNameFor(modelAd => Model.Ads.FirstOrDefault().ImageFilename)
            </th>
        <th></th>
        </tr>
@foreach (var ad in Model.Ads)    {
        <tr>
            <td>
                @Html.DisplayFor(modelAd => ad.Name)
            </td>
            <td>
                @Html.DisplayFor(modelAd => ad.Index)
            </td>
            <td>
                @Html.DisplayFor(modelAd => ad.FlightStart)
            </td>
            <td>
                @Html.DisplayFor(modelAd => ad.FlightEnd)
            </td>
            <td>
                @Html.DisplayFor(modelAd => ad.ImageFilename)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Ads", new { id = ad.Id }, null)
 |
                @Html.ActionLink("Remove from List", "RemoveAdFromBillboard", "Billboards", new { billboardId = Model.Id, adId = ad.Id }, null )
            </td>
        </tr>
}
    </table>    
</div>

AdLineup/Views/Billboards/Edit.cshtml
@model AdLineup.Models.Billboard

@{
    ViewBag.Title = "Edit Billboard";
@Styles.Render("~/Content/datetimepicker/css")
@Scripts.Render("~/bundles/datetimepicker")

}

<h2>Billboard: @Html.DisplayFor(model => model.Name)</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (User.IsInRole("Admin"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.AdFlowchartDiagramData, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AdFlowchartDiagramData, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AdFlowchartDiagramData, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdLineup/Views/Billboards/Index.cshtml
@model IEnumerable<AdLineup.Models.Billboard>

@{
    ViewBag.Title = "Index Billboard";
}

<h2>Billboards</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = 0, modelType = "" }, null) | 
    <a id="printerFriendlyLink" href="#">Printer Friendly View</a>
    <img id="printerFriendlyLoader" src="~/Content/images/linear-loader.gif" style="display: none;"/>
</p>
    <div id="printerFriendlyError" class="alert alert-danger" style="display: none;">
        <strong>Error:</strong>  Could not generate Printer Friendly View. Please try again.
    </div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Latitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitude)
        </th>
        @if (User.IsInRole("Admin"))
        {
            <th>
                @Html.DisplayNameFor(model => model.AdFlowchartDiagramData)
            </th>
        }
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Latitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longitude)
        </td>
        @if (User.IsInRole("Admin"))
        {
        <td>
                @Html.DisplayFor(modelItem => item.AdFlowchartDiagramData)
        </td>
        }
        <td>
            @Html.ActionLink("Ad Diagram", "BillboardAdsFlowchartDiagram", new { id = item.Id }) |
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<script src="~/Scripts/ViewScripts/index-view.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#printerFriendlyError").hide();
        storePrinterFriendlyData("@ViewBag.PrinterFriendlyUrl", "@ViewBag.AppEngineTimeout");
        $("#printerFriendlyLink").click(function () {
            viewReport(
                getPrinterFriendlyUrl(),
                getAppEngineTimeout(),
                $("#printerFriendlyError"),
                $("#printerFriendlyLink"),
                $("#printerFriendlyLoader")
            );
        });
    });
</script>